-- Wysker Watch — in-app notifications
--
-- Lightweight table for system-generated notices that appear inside the
-- app the next time the recipient opens it. Initial use-case: ownership-
-- transfer notices generated by the delete-account Edge Function when a
-- co-owned pet's primary owner deletes their account.
--
-- No email is sent here — email notifications are deferred to the
-- transactional email backlog alongside sitter/co-owner invite emails.

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,           -- e.g. 'ownership_transfer'
  message text not null,        -- human-readable string shown in the UI
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create index notifications_user_id_idx on public.notifications(user_id);
create index notifications_user_id_read_idx on public.notifications(user_id, read) where read = false;

alter table public.notifications enable row level security;

-- Users can only see their own notifications.
create policy "notifications_select_own" on public.notifications
  for select using (auth.uid() = user_id);

-- The delete-account Edge Function inserts rows using the service-role
-- client (which bypasses RLS), so no insert policy is needed for users.
-- We do allow users to mark their own notifications as read.
create policy "notifications_update_own" on public.notifications
  for update using (auth.uid() = user_id);

-- Users can dismiss/delete their own notifications.
create policy "notifications_delete_own" on public.notifications
  for delete using (auth.uid() = user_id);
